services:
  - type: web
    name: tutor-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    workingDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
