services:
  - type: web
    name: tutor-bot
    runtime: python # Use 'runtime' instead of 'env' for clarity
    workingDir: backend
    plan: free # Or your preferred plan
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0" # Be specific with Python versions if possible

    buildCommand: |
      # Install backend dependencies
      pip install -r requirements.txt
      # Navigate out of 'backend', into 'frontend', and build it
      cd ../frontend && npm install && npm run build

    startCommand: gunicorn --bind 0.0.0.0:${PORT} app:app